# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-06-17 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_album_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateTimeField(auto_now_add=True)),
                ('schedule_name', models.CharField(max_length=20)),
                ('schedule_telephone', models.CharField(max_length=11)),
                ('schedule_status', models.CharField(max_length=10)),
                ('schedule_call', models.IntegerField(default=0)),
                ('schedule_memo', models.CharField(max_length=1000)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
    ]
