# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-07-01 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='user',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
