# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-07-01 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_schedule_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='user',
            field=models.CharField(default='all', max_length=10),
        ),
    ]
