# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-07-30 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20180701_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_telephone',
            field=models.CharField(max_length=11, verbose_name='移动电话'),
        ),
    ]
