# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-08-10 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20180730_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_call',
            field=models.IntegerField(default=0, verbose_name='电话次数'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_memo',
            field=models.CharField(max_length=1000, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_name',
            field=models.CharField(max_length=20, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_status',
            field=models.CharField(max_length=10, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user',
            field=models.CharField(default='all', max_length=10, verbose_name='操作用户'),
        ),
    ]
